# Generated by Django 4.2.3 on 2023-07-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avicenna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='9972fa46-3732-4f8f-b048-12b166faf1ec', max_length=100, unique=True),
        ),
    ]
