# Generated by Django 4.2.3 on 2023-07-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avicenna', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='f7a8564c-4582-401e-a8f8-d32ea1a5e20c', max_length=100, unique=True),
        ),
    ]
