# Generated by Django 4.2.3 on 2023-07-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avicenna', '0003_alter_customuser_username_alter_patient_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='3a461168', max_length=100, unique=True),
        ),
    ]
