# Generated by Django 4.2.3 on 2023-07-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avicenna', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='2eca5d4a', max_length=100, unique=True),
        ),
    ]
