name: avicenna_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  add_2_calendar: ^2.2.3
  bloc: ^8.1.2
  dio: ^5.2.1+1
  equatable: ^2.0.5
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.1.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
